export type P7SecurityPlatform = "darwin" | "win32" | "linux";
export type P7SecurityLayer = 1 | 2 | 3 | 4;

export type AbuseCaseVariant = Readonly<{
  id: `P7-V-${string}-${string}-${string}`;
  testFile: string;
  testName: string;
  forbiddenEffects: readonly string[];
  evidenceFields: readonly string[];
}>;

export type AbuseCase = Readonly<{
  id: `P7-A-${string}-${string}`;
  invariantId: `P7-I-${string}-${string}`;
  risk: "critical" | "high" | "medium" | "low";
  minimumLayer: P7SecurityLayer;
  requiredLayers: readonly P7SecurityLayer[];
  variants: readonly AbuseCaseVariant[];
  expectedBoundary: string;
  expectedIncidentCode: string | null;
  supportedPlatforms: readonly P7SecurityPlatform[];
  p8Obligation: string | null;
}>;

type SecurityInvariant = Readonly<{
  id: `P7-I-${string}-${string}`;
  description: string;
}>;

const freeze = <T>(value: T): Readonly<T> => {
  if (Array.isArray(value)) {
    for (const item of value) {
      if (typeof item === "object" && item !== null) freeze(item);
    }
  } else if (typeof value === "object" && value !== null) {
    for (const child of Object.values(value)) {
      if (typeof child === "object" && child !== null) freeze(child);
    }
  }
  return Object.freeze(value);
};

export const P7_SECURITY_INVARIANTS: readonly SecurityInvariant[] = freeze([
  {
    id: "P7-I-RENDERER-001",
    description: "Renderer has bounded projections and typed intents only.",
  },
  {
    id: "P7-I-IPC-001",
    description: "IPC accepts exact operations from the trusted current frame only.",
  },
  {
    id: "P7-I-CREDENTIAL-001",
    description: "Raw credentials remain Main-owned and redacted at projections.",
  },
  {
    id: "P7-I-WORKSPACE-001",
    description: "File and Git effects stay inside the revalidated active grant.",
  },
  {
    id: "P7-I-DELIVERY-001",
    description: "Original workspace changes require a distinct Main approval.",
  },
  {
    id: "P7-I-TOOL-001",
    description: "Only declared, policy-admitted tool operations reach executors.",
  },
  {
    id: "P7-I-APPROVAL-001",
    description: "Approval evidence is exact-operation, exact-attempt, and one-shot.",
  },
  {
    id: "P7-I-MCP-001",
    description: "Loopback peers and protocol shapes are authenticated and bounded.",
  },
  {
    id: "P7-I-WORKER-001",
    description: "Workers receive admitted executables and closed capabilities.",
  },
  {
    id: "P7-I-NETWORK-001",
    description: "Renderer and isolated Workers cannot create undeclared network effects.",
  },
  {
    id: "P7-I-PROCESS-001",
    description: "Terminal paths settle state and release all privileged process resources.",
  },
  {
    id: "P7-I-PERSISTENCE-001",
    description: "Replayed or unauthorized durable records fail without a second effect.",
  },
  {
    id: "P7-I-REDACTION-001",
    description: "Events and diagnostics retain classification without protected user data.",
  },
  {
    id: "P7-I-ARTIFACT-001",
    description: "Artifacts require an external trust root, exact digest, and exact shape.",
  },
] as SecurityInvariant[]);

export const P7_ABUSE_OUTCOMES = freeze([
  "denied-safe",
  "unsupported-platform",
  "security-boundary-violated",
  "cleanup-incomplete",
  "evidence-incomplete",
  "test-harness-invalid",
] as const);

export const P7_ABUSE_INCIDENT_CODES = freeze([
  "invalid-config",
  "manifest-unavailable",
  "model-completion-refused",
  "model-request-rejected",
  "unsupported-tool",
  "workspace-unavailable",
  "worker-execution-failed",
] as const);

const MACOS_ONLY = ["darwin"] as const;
const P8 = "Implement and physically verify the equivalent boundary on Windows and Linux in P8.";
const NO_EFFECTS = ["executor-call", "workspace-write", "credential-projection"] as const;
const PROCESS_NO_EFFECTS = ["executor-call", "child-process", "terminal-completed"] as const;
const EVIDENCE = ["rejection-boundary", "outcome", "side-effect-count"] as const;

const makeCase = <
  const Id extends AbuseCase["id"],
  const InvariantId extends AbuseCase["invariantId"],
>(
  value: Omit<AbuseCase, "id" | "invariantId" | "variants"> & {
    id: Id;
    invariantId: InvariantId;
    testFile: string;
    variantSuffixes: readonly string[];
    forbiddenEffects: readonly string[];
    evidenceFields: readonly string[];
  },
): AbuseCase => {
  const { testFile, variantSuffixes, forbiddenEffects, evidenceFields, ...abuseCase } = value;
  const variantPrefix = value.id.replace("P7-A-", "P7-V-");
  return freeze({
    ...abuseCase,
    requiredLayers: [...value.requiredLayers],
    variants: variantSuffixes.map((suffix) => {
      const id = `${variantPrefix}-${suffix}` as AbuseCaseVariant["id"];
      return {
        id,
        testFile,
        testName: `${value.id} ${id}`,
        forbiddenEffects: [...forbiddenEffects],
        evidenceFields: [...evidenceFields],
      };
    }),
    supportedPlatforms: [...value.supportedPlatforms],
  }) as AbuseCase;
};

export const P7_ABUSE_CASES: readonly AbuseCase[] = freeze([
  makeCase({
    id: "P7-A-RENDERER-001",
    invariantId: "P7-I-RENDERER-001",
    risk: "critical",
    minimumLayer: 1,
    requiredLayers: [1],
    testFile: "tests/security/rendererIpcCredentialAbuse.test.ts",
    variantSuffixes: [
      "DIRECT-NODE",
      "DIRECT-ELECTRON",
      "PRIVILEGED-PROCESS",
      "SHELL",
      "PERSISTENCE",
      "FILESYSTEM",
      "GIT",
    ],
    expectedBoundary: "product-boundary-rules",
    expectedIncidentCode: null,
    forbiddenEffects: ["executor-call", "filesystem-read", "shell-spawn"],
    evidenceFields: EVIDENCE,
    supportedPlatforms: MACOS_ONLY,
    p8Obligation: P8,
  }),
  makeCase({
    id: "P7-A-RENDERER-002",
    invariantId: "P7-I-RENDERER-001",
    risk: "critical",
    minimumLayer: 1,
    requiredLayers: [1, 4],
    testFile: "tests/security/rendererIpcCredentialAbuse.test.ts",
    variantSuffixes: ["FETCH", "WEBSOCKET", "EVENTSOURCE", "XMLHTTPREQUEST", "WINDOW-REQUIRE"],
    expectedBoundary: "product-boundary-rules",
    expectedIncidentCode: null,
    forbiddenEffects: ["external-network", "credential-projection", "filesystem-read"],
    evidenceFields: EVIDENCE,
    supportedPlatforms: MACOS_ONLY,
    p8Obligation: P8,
  }),
  makeCase({
    id: "P7-A-IPC-001",
    invariantId: "P7-I-IPC-001",
    risk: "high",
    minimumLayer: 2,
    requiredLayers: [2],
    testFile: "tests/security/rendererIpcCredentialAbuse.test.ts",
    variantSuffixes: [
      "UNDECLARED-CHANNEL",
      "STALE-FRAME",
      "NON-MAIN-FRAME",
      "WRONG-SENDER",
      "REQUEST-AFTER-DISPOSAL",
    ],
    expectedBoundary: "desktopIpc",
    expectedIncidentCode: null,
    forbiddenEffects: NO_EFFECTS,
    evidenceFields: EVIDENCE,
    supportedPlatforms: MACOS_ONLY,
    p8Obligation: P8,
  }),
  makeCase({
    id: "P7-A-IPC-002",
    invariantId: "P7-I-IPC-001",
    risk: "high",
    minimumLayer: 2,
    requiredLayers: [2],
    testFile: "tests/security/rendererIpcCredentialAbuse.test.ts",
    variantSuffixes: [
      "UNKNOWN-KEYS",
      "PROTOTYPE-BEARING-INPUT",
      "UNEXPECTED-ARGUMENTS",
      "OVERSIZED-PAYLOAD",
    ],
    expectedBoundary: "desktopIpc payload validator",
    expectedIncidentCode: null,
    forbiddenEffects: ["executor-call", "persistence-write", "credential-projection"],
    evidenceFields: EVIDENCE,
    supportedPlatforms: MACOS_ONLY,
    p8Obligation: P8,
  }),
  makeCase({
    id: "P7-A-CREDENTIAL-001",
    invariantId: "P7-I-CREDENTIAL-001",
    risk: "critical",
    minimumLayer: 2,
    requiredLayers: [2, 4],
    testFile: "tests/security/rendererIpcCredentialAbuse.test.ts",
    variantSuffixes: [
      "PROVIDER-LIST-REDACTION",
      "PROVIDER-READ-REDACTION",
      "CHROMIUM-NO-STORE",
      "RENDERER-CACHE-ABSENCE",
    ],
    expectedBoundary: "Main provider projection",
    expectedIncidentCode: null,
    forbiddenEffects: ["credential-projection", "credential-cache", "renderer-secret"],
    evidenceFields: EVIDENCE,
    supportedPlatforms: MACOS_ONLY,
    p8Obligation: P8,
  }),
  makeCase({
    id: "P7-A-CREDENTIAL-002",
    invariantId: "P7-I-CREDENTIAL-001",
    risk: "critical",
    minimumLayer: 2,
    requiredLayers: [2],
    testFile: "tests/security/rendererIpcCredentialAbuse.test.ts",
    variantSuffixes: [
      "SENTINEL-WRITE-BACK",
      "CROSS-PROVIDER-SUBSTITUTION",
      "MISSING-STORED-KEY",
      "ANONYMOUS-FETCH-FALLBACK",
    ],
    expectedBoundary: "Main provider credential resolver",
    expectedIncidentCode: null,
    forbiddenEffects: ["credential-write", "cross-provider-effect", "anonymous-effect"],
    evidenceFields: EVIDENCE,
    supportedPlatforms: MACOS_ONLY,
    p8Obligation: P8,
  }),
  makeCase({
    id: "P7-A-CREDENTIAL-003",
    invariantId: "P7-I-CREDENTIAL-001",
    risk: "critical",
    minimumLayer: 2,
    requiredLayers: [2, 4],
    testFile: "tests/security/rendererIpcCredentialAbuse.test.ts",
    variantSuffixes: [
      "RENDERER-LEAKAGE",
      "LOG-LEAKAGE",
      "PERSISTENCE-LEAKAGE",
      "WORKER-ENVIRONMENT-LEAKAGE",
      "DIAGNOSTIC-LEAKAGE",
    ],
    expectedBoundary: "credential redaction boundary",
    expectedIncidentCode: null,
    forbiddenEffects: [
      "credential-projection",
      "credential-persistence",
      "worker-environment-secret",
    ],
    evidenceFields: ["redaction-boolean", "leakage-count", "side-effect-count"],
    supportedPlatforms: MACOS_ONLY,
    p8Obligation: P8,
  }),
  makeCase({
    id: "P7-A-WORKSPACE-001",
    invariantId: "P7-I-WORKSPACE-001",
    risk: "critical",
    minimumLayer: 2,
    requiredLayers: [2],
    testFile: "tests/security/workspaceToolApprovalAbuse.test.ts",
    variantSuffixes: [
      "TRAVERSAL",
      "ABSOLUTE-PATH",
      "EMBEDDED-NUL",
      "SYMLINK-ESCAPE",
      "WORKSPACE-EXTERNAL-READ",
      "WORKSPACE-EXTERNAL-WRITE",
    ],
    expectedBoundary: "workspace grant canonical path",
    expectedIncidentCode: "workspace-unavailable",
    forbiddenEffects: ["workspace-external-read", "workspace-external-write", "executor-call"],
    evidenceFields: EVIDENCE,
    supportedPlatforms: MACOS_ONLY,
    p8Obligation: P8,
  }),
  makeCase({
    id: "P7-A-WORKSPACE-002",
    invariantId: "P7-I-WORKSPACE-001",
    risk: "high",
    minimumLayer: 2,
    requiredLayers: [2],
    testFile: "tests/security/workspaceToolApprovalAbuse.test.ts",
    variantSuffixes: [
      "REPLACED-GIT-POINTER",
      "WRONG-CANONICAL-ROOT",
      "SUBDIRECTORY",
      "LINKED-WORKTREE",
      "REVOKED-GRANT",
    ],
    expectedBoundary: "canonical Git root revalidation",
    expectedIncidentCode: "workspace-unavailable",
    forbiddenEffects: ["workspace-write", "wrong-repository-effect", "grant-retention"],
    evidenceFields: EVIDENCE,
    supportedPlatforms: MACOS_ONLY,
    p8Obligation: P8,
  }),
  makeCase({
    id: "P7-A-WORKSPACE-003",
    invariantId: "P7-I-WORKSPACE-001",
    risk: "high",
    minimumLayer: 2,
    requiredLayers: [2],
    testFile: "tests/security/workspaceToolApprovalAbuse.test.ts",
    variantSuffixes: ["HOOKS", "FILTERS", "INCLUDES", "FSMONITOR", "DIRTY-TREE", "HEAD-DRIFT"],
    expectedBoundary: "Git safety preflight",
    expectedIncidentCode: "workspace-unavailable",
    forbiddenEffects: ["hook-execution", "filter-execution", "workspace-write"],
    evidenceFields: EVIDENCE,
    supportedPlatforms: MACOS_ONLY,
    p8Obligation: P8,
  }),
  makeCase({
    id: "P7-A-DELIVERY-001",
    invariantId: "P7-I-DELIVERY-001",
    risk: "critical",
    minimumLayer: 2,
    requiredLayers: [2],
    testFile: "tests/security/workspaceToolApprovalAbuse.test.ts",
    variantSuffixes: [
      "SOURCE-WRITE-BEFORE-APPLY-APPROVAL",
      "CONFLICTING-PATCH",
      "DIGEST-DRIFT",
      "MULTI-FILE-ATOMIC-DENIAL",
    ],
    expectedBoundary: "Main artifact applicator",
    expectedIncidentCode: null,
    forbiddenEffects: ["workspace-write", "executor-call", "partial-apply"],
    evidenceFields: EVIDENCE,
    supportedPlatforms: MACOS_ONLY,
    p8Obligation: P8,
  }),
  makeCase({
    id: "P7-A-DELIVERY-002",
    invariantId: "P7-I-DELIVERY-001",
    risk: "high",
    minimumLayer: 2,
    requiredLayers: [2],
    testFile: "tests/security/workspaceToolApprovalAbuse.test.ts",
    variantSuffixes: [
      "CONCURRENT-APPLY",
      "ALREADY-APPLIED-RETRY",
      "LOST-RESPONSE",
      "REPOSITORY-LOCK",
      "IDEMPOTENT-RECOVERY",
    ],
    expectedBoundary: "repository lock and artifact applicator",
    expectedIncidentCode: null,
    forbiddenEffects: ["duplicate-workspace-write", "duplicate-audit", "lock-residue"],
    evidenceFields: EVIDENCE,
    supportedPlatforms: MACOS_ONLY,
    p8Obligation: P8,
  }),
  makeCase({
    id: "P7-A-TOOL-001",
    invariantId: "P7-I-TOOL-001",
    risk: "high",
    minimumLayer: 2,
    requiredLayers: [2],
    testFile: "tests/security/workspaceToolApprovalAbuse.test.ts",
    variantSuffixes: [
      "UNKNOWN-TOOL",
      "MISSING-MANIFEST",
      "NO-POLICY",
      "CONFLICTING-POLICY",
      "MALFORMED-INPUT",
      "WIDENED-MANIFEST",
    ],
    expectedBoundary: "ToolGateway manifest and policy",
    expectedIncidentCode: "manifest-unavailable",
    forbiddenEffects: ["executor-call", "approval-creation", "audit-effect"],
    evidenceFields: EVIDENCE,
    supportedPlatforms: MACOS_ONLY,
    p8Obligation: P8,
  }),
  makeCase({
    id: "P7-A-TOOL-002",
    invariantId: "P7-I-TOOL-001",
    risk: "high",
    minimumLayer: 2,
    requiredLayers: [2, 3],
    testFile: "tests/security/workspaceToolApprovalAbuse.test.ts",
    variantSuffixes: [
      "INVALID-CREDENTIAL-REFERENCE",
      "STALE-AUTHORIZATION",
      "EXECUTOR-MISMATCH",
      "AMBIGUOUS-POST-EFFECT-RETRY",
    ],
    expectedBoundary: "ToolGateway authorization",
    expectedIncidentCode: "unsupported-tool",
    forbiddenEffects: ["executor-call", "credential-effect", "second-effect"],
    evidenceFields: EVIDENCE,
    supportedPlatforms: MACOS_ONLY,
    p8Obligation: P8,
  }),
  makeCase({
    id: "P7-A-APPROVAL-001",
    invariantId: "P7-I-APPROVAL-001",
    risk: "high",
    minimumLayer: 2,
    requiredLayers: [2],
    testFile: "tests/security/workspaceToolApprovalAbuse.test.ts",
    variantSuffixes: [
      "DENY",
      "EXPIRE",
      "CANCEL",
      "REUSE",
      "WRONG-OPERATION",
      "WRONG-ATTEMPT",
      "STALE-SNAPSHOT",
    ],
    expectedBoundary: "approval exact identity gate",
    expectedIncidentCode: null,
    forbiddenEffects: ["executor-call", "approval-reuse", "audit-effect"],
    evidenceFields: EVIDENCE,
    supportedPlatforms: MACOS_ONLY,
    p8Obligation: P8,
  }),
  makeCase({
    id: "P7-A-APPROVAL-002",
    invariantId: "P7-I-APPROVAL-001",
    risk: "high",
    minimumLayer: 2,
    requiredLayers: [2],
    testFile: "tests/security/workspaceToolApprovalAbuse.test.ts",
    variantSuffixes: [
      "PROTECTED-AS-WORKFLOW-FEEDBACK",
      "PROTECTED-AS-PUBLISH",
      "PROTECTED-AS-WORKSPACE-APPLY",
      "WORKFLOW-FEEDBACK-AS-PROTECTED",
      "WORKFLOW-FEEDBACK-AS-PUBLISH",
      "WORKFLOW-FEEDBACK-AS-WORKSPACE-APPLY",
      "PUBLISH-AS-PROTECTED",
      "PUBLISH-AS-WORKFLOW-FEEDBACK",
      "PUBLISH-AS-WORKSPACE-APPLY",
      "WORKSPACE-APPLY-AS-PROTECTED",
      "WORKSPACE-APPLY-AS-WORKFLOW-FEEDBACK",
      "WORKSPACE-APPLY-AS-PUBLISH",
    ],
    expectedBoundary: "approval operation and attempt binding",
    expectedIncidentCode: null,
    forbiddenEffects: ["executor-call", "workspace-write", "approval-reuse"],
    evidenceFields: EVIDENCE,
    supportedPlatforms: MACOS_ONLY,
    p8Obligation: P8,
  }),
  makeCase({
    id: "P7-A-MCP-001",
    invariantId: "P7-I-MCP-001",
    risk: "high",
    minimumLayer: 3,
    requiredLayers: [3],
    testFile: "tests/security/mcpWorkerProcessAbuse.test.ts",
    variantSuffixes: [
      "WRONG-LEASE",
      "WRONG-TOKEN",
      "WRONG-HOST",
      "WRONG-ORIGIN",
      "WRONG-USER-AGENT",
      "WRONG-METHOD",
      "WRONG-CONTENT-TYPE",
      "WRONG-MODEL",
      "INVALID-INITIALIZATION-ORDER",
    ],
    expectedBoundary: "Goose MCP and model loopback lease",
    expectedIncidentCode: "invalid-config",
    forbiddenEffects: ["model-invocation", "tool-invocation", "lease-retention"],
    evidenceFields: EVIDENCE,
    supportedPlatforms: MACOS_ONLY,
    p8Obligation: P8,
  }),
  makeCase({
    id: "P7-A-MCP-002",
    invariantId: "P7-I-MCP-001",
    risk: "high",
    minimumLayer: 3,
    requiredLayers: [3],
    testFile: "tests/security/mcpWorkerProcessAbuse.test.ts",
    variantSuffixes: [
      "MALFORMED-JSON",
      "MALFORMED-SSE",
      "OVERSIZED-BODY",
      "OVERSIZED-FRAME",
      "OVERSIZED-TREE",
      "DUPLICATE-IDENTITY",
      "REQUEST-AFTER-CLOSE",
      "IN-FLIGHT-CLOSE",
    ],
    expectedBoundary: "bounded MCP protocol parser",
    expectedIncidentCode: "invalid-config",
    forbiddenEffects: ["model-invocation", "tool-invocation", "child-process"],
    evidenceFields: EVIDENCE,
    supportedPlatforms: MACOS_ONLY,
    p8Obligation: P8,
  }),
  makeCase({
    id: "P7-A-MCP-003",
    invariantId: "P7-I-MCP-001",
    risk: "high",
    minimumLayer: 3,
    requiredLayers: [3],
    testFile: "tests/security/mcpWorkerProcessAbuse.test.ts",
    variantSuffixes: [
      "UNDECLARED-TOOL",
      "AMBIGUOUS-ALIAS",
      "INVALID-TOOL-COUNT",
      "UNMODELED-PROVIDER-FIELD",
    ],
    expectedBoundary: "Main model and MCP capability admission",
    expectedIncidentCode: "unsupported-tool",
    forbiddenEffects: ["model-invocation", "tool-invocation", "executor-call"],
    evidenceFields: EVIDENCE,
    supportedPlatforms: MACOS_ONLY,
    p8Obligation: P8,
  }),
  makeCase({
    id: "P7-A-WORKER-001",
    invariantId: "P7-I-WORKER-001",
    risk: "critical",
    minimumLayer: 3,
    requiredLayers: [3, 4],
    testFile: "tests/security/mcpWorkerProcessAbuse.test.ts",
    variantSuffixes: [
      "UNADMITTED-EXECUTABLE",
      "UNADMITTED-DIGEST",
      "WIDENED-CAPABILITIES",
      "INHERITED-ENVIRONMENT-SECRET",
    ],
    expectedBoundary: "Worker admission and closed environment",
    expectedIncidentCode: "invalid-config",
    forbiddenEffects: ["worker-environment-secret", "external-network", "child-process"],
    evidenceFields: EVIDENCE,
    supportedPlatforms: MACOS_ONLY,
    p8Obligation: P8,
  }),
  makeCase({
    id: "P7-A-NETWORK-001",
    invariantId: "P7-I-NETWORK-001",
    risk: "critical",
    minimumLayer: 3,
    requiredLayers: [3, 4],
    testFile: "tests/security/mcpWorkerProcessAbuse.test.ts",
    variantSuffixes: [
      "RENDERER-EXTERNAL-NETWORK",
      "WORKER-EXTERNAL-NETWORK",
      "UNDECLARED-LOOPBACK-DESTINATION",
    ],
    expectedBoundary: "Renderer and Worker network policy",
    expectedIncidentCode: null,
    forbiddenEffects: ["external-network", "undeclared-loopback", "credential-projection"],
    evidenceFields: EVIDENCE,
    supportedPlatforms: MACOS_ONLY,
    p8Obligation: P8,
  }),
  makeCase({
    id: "P7-A-PROCESS-001",
    invariantId: "P7-I-PROCESS-001",
    risk: "high",
    minimumLayer: 3,
    requiredLayers: [3],
    testFile: "tests/security/mcpWorkerProcessAbuse.test.ts",
    variantSuffixes: [
      "UNEXPECTED-CHILD",
      "OUTPUT-OVERFLOW",
      "TIMEOUT",
      "CRASH",
      "CANCELLATION",
      "NORMAL-LEADER-EXIT",
      "FAILING-LEADER-EXIT",
    ],
    expectedBoundary: "supervised Worker lifecycle",
    expectedIncidentCode: "worker-execution-failed",
    forbiddenEffects: PROCESS_NO_EFFECTS,
    evidenceFields: ["exit-shape", "pid-count", "cleanup-boolean"],
    supportedPlatforms: MACOS_ONLY,
    p8Obligation: P8,
  }),
  makeCase({
    id: "P7-A-PROCESS-002",
    invariantId: "P7-I-PROCESS-001",
    risk: "high",
    minimumLayer: 3,
    requiredLayers: [3, 4],
    testFile: "tests/security/mcpWorkerProcessAbuse.test.ts",
    variantSuffixes: [
      "PARENT-DEATH",
      "CLOSE-RACE",
      "CLEANUP-RETRY",
      "RESIDUAL-PROCESS-SCAN",
      "RESIDUAL-PRIVATE-ROOT-SCAN",
      "RESIDUAL-WORKTREE-SCAN",
      "RESIDUAL-REPOSITORY-LOCK-SCAN",
    ],
    expectedBoundary: "supervisor cleanup and private-root release",
    expectedIncidentCode: "worker-execution-failed",
    forbiddenEffects: ["child-process", "private-root-residue", "lock-residue"],
    evidenceFields: ["exit-shape", "residue-count", "cleanup-boolean"],
    supportedPlatforms: MACOS_ONLY,
    p8Obligation: P8,
  }),
  makeCase({
    id: "P7-A-PERSISTENCE-001",
    invariantId: "P7-I-PERSISTENCE-001",
    risk: "high",
    minimumLayer: 2,
    requiredLayers: [2],
    testFile: "tests/security/persistenceArtifactRedactionAbuse.test.ts",
    variantSuffixes: [
      "STALE-CAS",
      "CONFLICTING-DUPLICATE",
      "CROSS-OWNER-RECORD",
      "CROSS-ATTEMPT-RECORD",
      "SEQUENCE-REGRESSION",
      "REPLAY",
    ],
    expectedBoundary: "SQLite persistence CAS and identity validation",
    expectedIncidentCode: null,
    forbiddenEffects: ["persistence-rewrite", "second-effect", "terminal-completed"],
    evidenceFields: EVIDENCE,
    supportedPlatforms: MACOS_ONLY,
    p8Obligation: P8,
  }),
  makeCase({
    id: "P7-A-PERSISTENCE-002",
    invariantId: "P7-I-PERSISTENCE-001",
    risk: "high",
    minimumLayer: 2,
    requiredLayers: [2],
    testFile: "tests/security/persistenceArtifactRedactionAbuse.test.ts",
    variantSuffixes: [
      "UNKNOWN-KEYS",
      "TRUNCATED-PROTOCOL",
      "TRUNCATED-DATABASE",
      "DIGEST-TAMPER",
      "INVALID-SQLITE",
      "CLOSED-PORT",
    ],
    expectedBoundary: "SQLite protocol and digest validation",
    expectedIncidentCode: null,
    forbiddenEffects: ["persistence-rewrite", "authority-substitution", "second-effect"],
    evidenceFields: EVIDENCE,
    supportedPlatforms: MACOS_ONLY,
    p8Obligation: P8,
  }),
  makeCase({
    id: "P7-A-REDACTION-001",
    invariantId: "P7-I-REDACTION-001",
    risk: "critical",
    minimumLayer: 2,
    requiredLayers: [2, 3],
    testFile: "tests/security/persistenceArtifactRedactionAbuse.test.ts",
    variantSuffixes: [
      "CREDENTIAL",
      "PATH",
      "PROMPT",
      "COMPLETION",
      "TOOL-ARGUMENT",
      "CONTENT-REFERENCE",
      "PATCH",
      "ENVIRONMENT-TEXT",
    ],
    expectedBoundary: "diagnostic and audit redaction",
    expectedIncidentCode: null,
    forbiddenEffects: ["credential-projection", "sensitive-log", "user-path-leak"],
    evidenceFields: ["redaction-boolean", "leakage-count", "bounded-length"],
    supportedPlatforms: MACOS_ONLY,
    p8Obligation: P8,
  }),
  makeCase({
    id: "P7-A-REDACTION-002",
    invariantId: "P7-I-REDACTION-001",
    risk: "high",
    minimumLayer: 2,
    requiredLayers: [2],
    testFile: "tests/security/persistenceArtifactRedactionAbuse.test.ts",
    variantSuffixes: [
      "REJECTED-MODEL-FALSE-COMPLETED",
      "REJECTED-MODEL-FALSE-UNCHANGED",
      "REJECTED-TOOL-FALSE-COMPLETED",
      "REJECTED-TOOL-FALSE-UNCHANGED",
      "REJECTED-WORKER-FALSE-COMPLETED",
      "REJECTED-WORKER-FALSE-UNCHANGED",
    ],
    expectedBoundary: "incident and terminal projection",
    expectedIncidentCode: "worker-execution-failed",
    forbiddenEffects: ["terminal-completed", "successful-artifact", "unchanged-projection"],
    evidenceFields: ["terminal-status", "incident-code", "artifact-count"],
    supportedPlatforms: MACOS_ONLY,
    p8Obligation: P8,
  }),
  makeCase({
    id: "P7-A-ARTIFACT-001",
    invariantId: "P7-I-ARTIFACT-001",
    risk: "critical",
    minimumLayer: 2,
    requiredLayers: [1, 2, 4],
    testFile: "tests/security/persistenceArtifactRedactionAbuse.test.ts",
    variantSuffixes: [
      "SELF-AUTHORIZING-MANIFEST",
      "WRONG-DIGEST",
      "WRONG-ARCHITECTURE",
      "SYMLINK",
      "UNEXPECTED-FILE",
      "FEATURE-WIDENING",
      "UNSAFE-DEPENDENCY",
      "MISSING-LICENSE",
      "MISSING-SBOM",
      "MISSING-AUDIT",
      "PACKAGED-SOURCE-COPY-DRIFT",
    ],
    expectedBoundary: "artifact trust root and package verifier",
    expectedIncidentCode: null,
    forbiddenEffects: ["artifact-admission", "feature-widening", "source-copy-drift"],
    evidenceFields: ["digest-match", "shape-match", "license-evidence"],
    supportedPlatforms: MACOS_ONLY,
    p8Obligation: P8,
  }),
] as AbuseCase[]);
