export type P7SecurityPlatform = "darwin" | "win32" | "linux";
export type P7SecurityLayer = 1 | 2 | 3 | 4;

export type AbuseCase = Readonly<{
  id: `P7-A-${string}-${string}`;
  invariantId: `P7-I-${string}-${string}`;
  risk: "critical" | "high" | "medium" | "low";
  minimumLayer: P7SecurityLayer;
  requiredLayers: readonly P7SecurityLayer[];
  testFile: string;
  testName: string;
  expectedBoundary: string;
  expectedIncidentCode: string | null;
  forbiddenEffects: readonly string[];
  evidenceFields: readonly string[];
  supportedPlatforms: readonly P7SecurityPlatform[];
  p8Obligation: string | null;
}>;

type SecurityInvariant = Readonly<{
  id: `P7-I-${string}-${string}`;
  description: string;
}>;

const freeze = <T>(value: T): Readonly<T> => {
  if (Array.isArray(value)) {
    for (const item of value) {
      if (typeof item === "object" && item !== null) freeze(item);
    }
  } else if (typeof value === "object" && value !== null) {
    for (const child of Object.values(value)) {
      if (typeof child === "object" && child !== null) freeze(child);
    }
  }
  return Object.freeze(value);
};

export const P7_SECURITY_INVARIANTS: readonly SecurityInvariant[] = freeze([
  {
    id: "P7-I-RENDERER-001",
    description: "Renderer has bounded projections and typed intents only.",
  },
  {
    id: "P7-I-IPC-001",
    description: "IPC accepts exact operations from the trusted current frame only.",
  },
  {
    id: "P7-I-CREDENTIAL-001",
    description: "Raw credentials remain Main-owned and redacted at projections.",
  },
  {
    id: "P7-I-WORKSPACE-001",
    description: "File and Git effects stay inside the revalidated active grant.",
  },
  {
    id: "P7-I-DELIVERY-001",
    description: "Original workspace changes require a distinct Main approval.",
  },
  {
    id: "P7-I-TOOL-001",
    description: "Only declared, policy-admitted tool operations reach executors.",
  },
  {
    id: "P7-I-APPROVAL-001",
    description: "Approval evidence is exact-operation, exact-attempt, and one-shot.",
  },
  {
    id: "P7-I-MCP-001",
    description: "Loopback peers and protocol shapes are authenticated and bounded.",
  },
  {
    id: "P7-I-WORKER-001",
    description: "Workers receive admitted executables and closed capabilities.",
  },
  {
    id: "P7-I-NETWORK-001",
    description: "Renderer and isolated Workers cannot create undeclared network effects.",
  },
  {
    id: "P7-I-PROCESS-001",
    description: "Terminal paths settle state and release all privileged process resources.",
  },
  {
    id: "P7-I-PERSISTENCE-001",
    description: "Replayed or unauthorized durable records fail without a second effect.",
  },
  {
    id: "P7-I-REDACTION-001",
    description: "Events and diagnostics retain classification without protected user data.",
  },
  {
    id: "P7-I-ARTIFACT-001",
    description: "Artifacts require an external trust root, exact digest, and exact shape.",
  },
] as SecurityInvariant[]);

export const P7_ABUSE_OUTCOMES = freeze([
  "denied-safe",
  "unsupported-platform",
  "security-boundary-violated",
  "cleanup-incomplete",
  "evidence-incomplete",
  "test-harness-invalid",
] as const);

export const P7_ABUSE_INCIDENT_CODES = freeze([
  "invalid-config",
  "manifest-unavailable",
  "model-completion-refused",
  "model-request-rejected",
  "unsupported-tool",
  "workspace-unavailable",
  "worker-execution-failed",
] as const);

const MACOS_ONLY = ["darwin"] as const;
const P8 = "Implement and physically verify the equivalent boundary on Windows and Linux in P8.";
const NO_EFFECTS = ["executor-call", "workspace-write", "credential-projection"] as const;
const PROCESS_NO_EFFECTS = ["executor-call", "child-process", "terminal-completed"] as const;
const EVIDENCE = ["rejection-boundary", "outcome", "side-effect-count"] as const;

const makeCase = <
  const Id extends AbuseCase["id"],
  const InvariantId extends AbuseCase["invariantId"],
>(
  value: Omit<AbuseCase, "id" | "invariantId"> & { id: Id; invariantId: InvariantId },
): AbuseCase =>
  freeze({
    ...value,
    forbiddenEffects: [...value.forbiddenEffects],
    evidenceFields: [...value.evidenceFields],
    supportedPlatforms: [...value.supportedPlatforms],
    requiredLayers: [...value.requiredLayers],
  }) as AbuseCase;

export const P7_ABUSE_CASES: readonly AbuseCase[] = freeze([
  makeCase({
    id: "P7-A-RENDERER-001",
    invariantId: "P7-I-RENDERER-001",
    risk: "critical",
    minimumLayer: 1,
    requiredLayers: [1],
    testFile: "tests/security/rendererIpcCredentialAbuse.test.ts",
    testName: "P7-A-RENDERER-001 rejects privileged renderer imports",
    expectedBoundary: "product-boundary-rules",
    expectedIncidentCode: null,
    forbiddenEffects: ["executor-call", "filesystem-read", "shell-spawn"],
    evidenceFields: EVIDENCE,
    supportedPlatforms: MACOS_ONLY,
    p8Obligation: P8,
  }),
  makeCase({
    id: "P7-A-RENDERER-002",
    invariantId: "P7-I-RENDERER-001",
    risk: "critical",
    minimumLayer: 1,
    requiredLayers: [1, 4],
    testFile: "tests/security/rendererIpcCredentialAbuse.test.ts",
    testName: "P7-A-RENDERER-002 rejects renderer network escape",
    expectedBoundary: "product-boundary-rules",
    expectedIncidentCode: null,
    forbiddenEffects: ["external-network", "credential-projection", "filesystem-read"],
    evidenceFields: EVIDENCE,
    supportedPlatforms: MACOS_ONLY,
    p8Obligation: P8,
  }),
  makeCase({
    id: "P7-A-IPC-001",
    invariantId: "P7-I-IPC-001",
    risk: "high",
    minimumLayer: 2,
    requiredLayers: [2],
    testFile: "tests/security/rendererIpcCredentialAbuse.test.ts",
    testName: "P7-A-IPC-001 rejects untrusted IPC callers",
    expectedBoundary: "desktopIpc",
    expectedIncidentCode: null,
    forbiddenEffects: NO_EFFECTS,
    evidenceFields: EVIDENCE,
    supportedPlatforms: MACOS_ONLY,
    p8Obligation: P8,
  }),
  makeCase({
    id: "P7-A-IPC-002",
    invariantId: "P7-I-IPC-001",
    risk: "high",
    minimumLayer: 2,
    requiredLayers: [2],
    testFile: "tests/security/rendererIpcCredentialAbuse.test.ts",
    testName: "P7-A-IPC-002 rejects malformed IPC payloads",
    expectedBoundary: "desktopIpc payload validator",
    expectedIncidentCode: null,
    forbiddenEffects: ["executor-call", "persistence-write", "credential-projection"],
    evidenceFields: EVIDENCE,
    supportedPlatforms: MACOS_ONLY,
    p8Obligation: P8,
  }),
  makeCase({
    id: "P7-A-CREDENTIAL-001",
    invariantId: "P7-I-CREDENTIAL-001",
    risk: "critical",
    minimumLayer: 2,
    requiredLayers: [2, 4],
    testFile: "tests/security/rendererIpcCredentialAbuse.test.ts",
    testName: "P7-A-CREDENTIAL-001 redacts provider reads",
    expectedBoundary: "Main provider projection",
    expectedIncidentCode: null,
    forbiddenEffects: ["credential-projection", "credential-cache", "renderer-secret"],
    evidenceFields: EVIDENCE,
    supportedPlatforms: MACOS_ONLY,
    p8Obligation: P8,
  }),
  makeCase({
    id: "P7-A-CREDENTIAL-002",
    invariantId: "P7-I-CREDENTIAL-001",
    risk: "critical",
    minimumLayer: 2,
    requiredLayers: [2],
    testFile: "tests/security/rendererIpcCredentialAbuse.test.ts",
    testName: "P7-A-CREDENTIAL-002 rejects credential substitution",
    expectedBoundary: "Main provider credential resolver",
    expectedIncidentCode: null,
    forbiddenEffects: ["credential-write", "cross-provider-effect", "anonymous-effect"],
    evidenceFields: EVIDENCE,
    supportedPlatforms: MACOS_ONLY,
    p8Obligation: P8,
  }),
  makeCase({
    id: "P7-A-CREDENTIAL-003",
    invariantId: "P7-I-CREDENTIAL-001",
    risk: "critical",
    minimumLayer: 2,
    requiredLayers: [2, 4],
    testFile: "tests/security/rendererIpcCredentialAbuse.test.ts",
    testName: "P7-A-CREDENTIAL-003 blocks credential leakage",
    expectedBoundary: "credential redaction boundary",
    expectedIncidentCode: null,
    forbiddenEffects: [
      "credential-projection",
      "credential-persistence",
      "worker-environment-secret",
    ],
    evidenceFields: ["redaction-boolean", "leakage-count", "side-effect-count"],
    supportedPlatforms: MACOS_ONLY,
    p8Obligation: P8,
  }),
  makeCase({
    id: "P7-A-WORKSPACE-001",
    invariantId: "P7-I-WORKSPACE-001",
    risk: "critical",
    minimumLayer: 2,
    requiredLayers: [2],
    testFile: "tests/security/workspaceToolApprovalAbuse.test.ts",
    testName: "P7-A-WORKSPACE-001 rejects workspace scope escapes",
    expectedBoundary: "workspace grant canonical path",
    expectedIncidentCode: "workspace-unavailable",
    forbiddenEffects: ["workspace-external-read", "workspace-external-write", "executor-call"],
    evidenceFields: EVIDENCE,
    supportedPlatforms: MACOS_ONLY,
    p8Obligation: P8,
  }),
  makeCase({
    id: "P7-A-WORKSPACE-002",
    invariantId: "P7-I-WORKSPACE-001",
    risk: "high",
    minimumLayer: 2,
    requiredLayers: [2],
    testFile: "tests/security/workspaceToolApprovalAbuse.test.ts",
    testName: "P7-A-WORKSPACE-002 rejects Git identity drift",
    expectedBoundary: "canonical Git root revalidation",
    expectedIncidentCode: "workspace-unavailable",
    forbiddenEffects: ["workspace-write", "wrong-repository-effect", "grant-retention"],
    evidenceFields: EVIDENCE,
    supportedPlatforms: MACOS_ONLY,
    p8Obligation: P8,
  }),
  makeCase({
    id: "P7-A-WORKSPACE-003",
    invariantId: "P7-I-WORKSPACE-001",
    risk: "high",
    minimumLayer: 2,
    requiredLayers: [2],
    testFile: "tests/security/workspaceToolApprovalAbuse.test.ts",
    testName: "P7-A-WORKSPACE-003 rejects Git hook and state indirection",
    expectedBoundary: "Git safety preflight",
    expectedIncidentCode: "workspace-unavailable",
    forbiddenEffects: ["hook-execution", "filter-execution", "workspace-write"],
    evidenceFields: EVIDENCE,
    supportedPlatforms: MACOS_ONLY,
    p8Obligation: P8,
  }),
  makeCase({
    id: "P7-A-DELIVERY-001",
    invariantId: "P7-I-DELIVERY-001",
    risk: "critical",
    minimumLayer: 2,
    requiredLayers: [2],
    testFile: "tests/security/workspaceToolApprovalAbuse.test.ts",
    testName: "P7-A-DELIVERY-001 requires apply approval and revalidation",
    expectedBoundary: "Main artifact applicator",
    expectedIncidentCode: null,
    forbiddenEffects: ["workspace-write", "executor-call", "partial-apply"],
    evidenceFields: EVIDENCE,
    supportedPlatforms: MACOS_ONLY,
    p8Obligation: P8,
  }),
  makeCase({
    id: "P7-A-DELIVERY-002",
    invariantId: "P7-I-DELIVERY-001",
    risk: "high",
    minimumLayer: 2,
    requiredLayers: [2],
    testFile: "tests/security/workspaceToolApprovalAbuse.test.ts",
    testName: "P7-A-DELIVERY-002 makes apply retries idempotent",
    expectedBoundary: "repository lock and artifact applicator",
    expectedIncidentCode: null,
    forbiddenEffects: ["duplicate-workspace-write", "duplicate-audit", "lock-residue"],
    evidenceFields: EVIDENCE,
    supportedPlatforms: MACOS_ONLY,
    p8Obligation: P8,
  }),
  makeCase({
    id: "P7-A-TOOL-001",
    invariantId: "P7-I-TOOL-001",
    risk: "high",
    minimumLayer: 2,
    requiredLayers: [2],
    testFile: "tests/security/workspaceToolApprovalAbuse.test.ts",
    testName: "P7-A-TOOL-001 rejects undeclared or unpolicied tools",
    expectedBoundary: "ToolGateway manifest and policy",
    expectedIncidentCode: "manifest-unavailable",
    forbiddenEffects: ["executor-call", "approval-creation", "audit-effect"],
    evidenceFields: EVIDENCE,
    supportedPlatforms: MACOS_ONLY,
    p8Obligation: P8,
  }),
  makeCase({
    id: "P7-A-TOOL-002",
    invariantId: "P7-I-TOOL-001",
    risk: "high",
    minimumLayer: 2,
    requiredLayers: [2, 3],
    testFile: "tests/security/workspaceToolApprovalAbuse.test.ts",
    testName: "P7-A-TOOL-002 rejects stale tool authorization",
    expectedBoundary: "ToolGateway authorization",
    expectedIncidentCode: "unsupported-tool",
    forbiddenEffects: ["executor-call", "credential-effect", "second-effect"],
    evidenceFields: EVIDENCE,
    supportedPlatforms: MACOS_ONLY,
    p8Obligation: P8,
  }),
  makeCase({
    id: "P7-A-APPROVAL-001",
    invariantId: "P7-I-APPROVAL-001",
    risk: "high",
    minimumLayer: 2,
    requiredLayers: [2],
    testFile: "tests/security/workspaceToolApprovalAbuse.test.ts",
    testName: "P7-A-APPROVAL-001 rejects replayed approvals",
    expectedBoundary: "approval exact identity gate",
    expectedIncidentCode: null,
    forbiddenEffects: ["executor-call", "approval-reuse", "audit-effect"],
    evidenceFields: EVIDENCE,
    supportedPlatforms: MACOS_ONLY,
    p8Obligation: P8,
  }),
  makeCase({
    id: "P7-A-APPROVAL-002",
    invariantId: "P7-I-APPROVAL-001",
    risk: "high",
    minimumLayer: 2,
    requiredLayers: [2],
    testFile: "tests/security/workspaceToolApprovalAbuse.test.ts",
    testName: "P7-A-APPROVAL-002 rejects approval substitution",
    expectedBoundary: "approval operation and attempt binding",
    expectedIncidentCode: null,
    forbiddenEffects: ["executor-call", "workspace-write", "approval-reuse"],
    evidenceFields: EVIDENCE,
    supportedPlatforms: MACOS_ONLY,
    p8Obligation: P8,
  }),
  makeCase({
    id: "P7-A-MCP-001",
    invariantId: "P7-I-MCP-001",
    risk: "high",
    minimumLayer: 3,
    requiredLayers: [3],
    testFile: "tests/security/mcpWorkerProcessAbuse.test.ts",
    testName: "P7-A-MCP-001 rejects unauthenticated loopback peers",
    expectedBoundary: "Goose MCP and model loopback lease",
    expectedIncidentCode: "invalid-config",
    forbiddenEffects: ["model-invocation", "tool-invocation", "lease-retention"],
    evidenceFields: EVIDENCE,
    supportedPlatforms: MACOS_ONLY,
    p8Obligation: P8,
  }),
  makeCase({
    id: "P7-A-MCP-002",
    invariantId: "P7-I-MCP-001",
    risk: "high",
    minimumLayer: 3,
    requiredLayers: [3],
    testFile: "tests/security/mcpWorkerProcessAbuse.test.ts",
    testName: "P7-A-MCP-002 rejects malformed or oversized protocol frames",
    expectedBoundary: "bounded MCP protocol parser",
    expectedIncidentCode: "invalid-config",
    forbiddenEffects: ["model-invocation", "tool-invocation", "child-process"],
    evidenceFields: EVIDENCE,
    supportedPlatforms: MACOS_ONLY,
    p8Obligation: P8,
  }),
  makeCase({
    id: "P7-A-MCP-003",
    invariantId: "P7-I-MCP-001",
    risk: "high",
    minimumLayer: 3,
    requiredLayers: [3],
    testFile: "tests/security/mcpWorkerProcessAbuse.test.ts",
    testName: "P7-A-MCP-003 rejects undeclared and ambiguous model tools",
    expectedBoundary: "Main model and MCP capability admission",
    expectedIncidentCode: "unsupported-tool",
    forbiddenEffects: ["model-invocation", "tool-invocation", "executor-call"],
    evidenceFields: EVIDENCE,
    supportedPlatforms: MACOS_ONLY,
    p8Obligation: P8,
  }),
  makeCase({
    id: "P7-A-WORKER-001",
    invariantId: "P7-I-WORKER-001",
    risk: "critical",
    minimumLayer: 3,
    requiredLayers: [3, 4],
    testFile: "tests/security/mcpWorkerProcessAbuse.test.ts",
    testName: "P7-A-WORKER-001 rejects unadmitted Worker capabilities",
    expectedBoundary: "Worker admission and closed environment",
    expectedIncidentCode: "invalid-config",
    forbiddenEffects: ["worker-environment-secret", "external-network", "child-process"],
    evidenceFields: EVIDENCE,
    supportedPlatforms: MACOS_ONLY,
    p8Obligation: P8,
  }),
  makeCase({
    id: "P7-A-NETWORK-001",
    invariantId: "P7-I-NETWORK-001",
    risk: "critical",
    minimumLayer: 3,
    requiredLayers: [3, 4],
    testFile: "tests/security/mcpWorkerProcessAbuse.test.ts",
    testName: "P7-A-NETWORK-001 blocks undeclared network effects",
    expectedBoundary: "Renderer and Worker network policy",
    expectedIncidentCode: null,
    forbiddenEffects: ["external-network", "undeclared-loopback", "credential-projection"],
    evidenceFields: EVIDENCE,
    supportedPlatforms: MACOS_ONLY,
    p8Obligation: P8,
  }),
  makeCase({
    id: "P7-A-PROCESS-001",
    invariantId: "P7-I-PROCESS-001",
    risk: "high",
    minimumLayer: 3,
    requiredLayers: [3],
    testFile: "tests/security/mcpWorkerProcessAbuse.test.ts",
    testName: "P7-A-PROCESS-001 bounds Worker process outcomes",
    expectedBoundary: "supervised Worker lifecycle",
    expectedIncidentCode: "worker-execution-failed",
    forbiddenEffects: PROCESS_NO_EFFECTS,
    evidenceFields: ["exit-shape", "pid-count", "cleanup-boolean"],
    supportedPlatforms: MACOS_ONLY,
    p8Obligation: P8,
  }),
  makeCase({
    id: "P7-A-PROCESS-002",
    invariantId: "P7-I-PROCESS-001",
    risk: "high",
    minimumLayer: 3,
    requiredLayers: [3, 4],
    testFile: "tests/security/mcpWorkerProcessAbuse.test.ts",
    testName: "P7-A-PROCESS-002 cleans Worker process groups",
    expectedBoundary: "supervisor cleanup and private-root release",
    expectedIncidentCode: "worker-execution-failed",
    forbiddenEffects: ["child-process", "private-root-residue", "lock-residue"],
    evidenceFields: ["exit-shape", "residue-count", "cleanup-boolean"],
    supportedPlatforms: MACOS_ONLY,
    p8Obligation: P8,
  }),
  makeCase({
    id: "P7-A-PERSISTENCE-001",
    invariantId: "P7-I-PERSISTENCE-001",
    risk: "high",
    minimumLayer: 2,
    requiredLayers: [2],
    testFile: "tests/security/persistenceArtifactRedactionAbuse.test.ts",
    testName: "P7-A-PERSISTENCE-001 rejects replay and stale records",
    expectedBoundary: "SQLite persistence CAS and identity validation",
    expectedIncidentCode: null,
    forbiddenEffects: ["persistence-rewrite", "second-effect", "terminal-completed"],
    evidenceFields: EVIDENCE,
    supportedPlatforms: MACOS_ONLY,
    p8Obligation: P8,
  }),
  makeCase({
    id: "P7-A-PERSISTENCE-002",
    invariantId: "P7-I-PERSISTENCE-001",
    risk: "high",
    minimumLayer: 2,
    requiredLayers: [2],
    testFile: "tests/security/persistenceArtifactRedactionAbuse.test.ts",
    testName: "P7-A-PERSISTENCE-002 rejects malformed and tampered persistence",
    expectedBoundary: "SQLite protocol and digest validation",
    expectedIncidentCode: null,
    forbiddenEffects: ["persistence-rewrite", "authority-substitution", "second-effect"],
    evidenceFields: EVIDENCE,
    supportedPlatforms: MACOS_ONLY,
    p8Obligation: P8,
  }),
  makeCase({
    id: "P7-A-REDACTION-001",
    invariantId: "P7-I-REDACTION-001",
    risk: "critical",
    minimumLayer: 2,
    requiredLayers: [2, 3],
    testFile: "tests/security/persistenceArtifactRedactionAbuse.test.ts",
    testName: "P7-A-REDACTION-001 removes protected values from evidence",
    expectedBoundary: "diagnostic and audit redaction",
    expectedIncidentCode: null,
    forbiddenEffects: ["credential-projection", "sensitive-log", "user-path-leak"],
    evidenceFields: ["redaction-boolean", "leakage-count", "bounded-length"],
    supportedPlatforms: MACOS_ONLY,
    p8Obligation: P8,
  }),
  makeCase({
    id: "P7-A-REDACTION-002",
    invariantId: "P7-I-REDACTION-001",
    risk: "high",
    minimumLayer: 2,
    requiredLayers: [2],
    testFile: "tests/security/persistenceArtifactRedactionAbuse.test.ts",
    testName: "P7-A-REDACTION-002 prevents false terminal success",
    expectedBoundary: "incident and terminal projection",
    expectedIncidentCode: "worker-execution-failed",
    forbiddenEffects: ["terminal-completed", "successful-artifact", "unchanged-projection"],
    evidenceFields: ["terminal-status", "incident-code", "artifact-count"],
    supportedPlatforms: MACOS_ONLY,
    p8Obligation: P8,
  }),
  makeCase({
    id: "P7-A-ARTIFACT-001",
    invariantId: "P7-I-ARTIFACT-001",
    risk: "critical",
    minimumLayer: 2,
    requiredLayers: [1, 2, 4],
    testFile: "tests/security/persistenceArtifactRedactionAbuse.test.ts",
    testName: "P7-A-ARTIFACT-001 rejects untrusted artifact and package substitutions",
    expectedBoundary: "artifact trust root and package verifier",
    expectedIncidentCode: null,
    forbiddenEffects: ["artifact-admission", "feature-widening", "source-copy-drift"],
    evidenceFields: ["digest-match", "shape-match", "license-evidence"],
    supportedPlatforms: MACOS_ONLY,
    p8Obligation: P8,
  }),
] as AbuseCase[]);
